### ISSUE TITLE
Autoplay error

### ISSUE THREAD

**Issue by zerofelx** [Aaron00101010/vue-split-carousel#2]
I'm using the carousel and even though I have the :autoplay set to false, it keeps moving by itself. (The VueDevtools inform me that autoplay is false but still plays on its own)

Code:
`
            <split-carousel :speed="400" :item-width="300" :autoplay="false" :loop="false" :display-amount="6" item-align="left">
                <split-carousel-item v-for="episode in season.episodes" :key="episode.id">
                    <p>{{ episode.name }}</p>
                </split-carousel-item>
            </split-carousel>
`

**Comment by Aaron00101010** [comment]
@zerofelx  this issue should be fix in v1.1.0 😸

**Comment by fedorovvldmr** [comment]
I'm using version 1.1.0 and still autoplay won't turn off

**Comment by Aaron00101010** [comment]
@fedorovvldmr that's my mistake, I forget rebuild dist files before release package,now you can try version v1.1.1 . thanks for your feedback
