### ISSUE TITLE
VueJS 3 compatibility

### ISSUE THREAD

**Issue by djcaesar9114** [Aaron00101010/vue-split-carousel#3]
Hello,
For the moment it doesn't work with Vue3. :(

**Comment by Aaron00101010** [comment]
WIP 😄

**Comment by djcaesar9114** [comment]
Can't wait! Have you planned on a release date?

**Comment by Aaron00101010** [comment]
@djcaesar9114  I plan to finish it over this weekend 😿

**Comment by djcaesar9114** [comment]
Wow, that would be awesome. Thanks ;)

**Comment by Aaron00101010** [comment]
@djcaesar9114  2.x version is support vue 3 now 🥳

**Comment by djcaesar9114** [comment]
I'm testing it this week! Thanks Aaron :)
