### ISSUE TITLE
Nuxt.js Integration

### ISSUE THREAD

**Issue by JVillator0** [Aaron00101010/vue-split-carousel#4]
Hi, I tried to integrate this carousel with a Nuxt.js project, but couldn't get it to work.

The most logical option is for [local component](https://github.com/Aaron00101010/vue-split-carousel#local-component), but it doesn't work, throwing the following error
```
Object (...) is not a function
```
It also didn't work importing a plugin file that will use the Split Carousel component in `nuxt.config.js` .

`vue-split-carousel.js`:
```js
import Vue from 'vue'
import SplitCarousel from 'vue-split-carousel'

Vue.use(SplitCarousel)
// Vue.use(SplitCarousel, { prefix: 'El' }) // It didn't work either
```
`nuxt.config.js`:
```js
export default {
  ...,
  plugins: [
    '~/plugins/vue-split-carousel.js'
  ],
}
```

Okay so, any ideas how to integrate to a project in Nuxt.js?

**Comment by williamcruzme** [comment]
Please use the Client Mode of Nuxt.js

**Comment by Aaron00101010** [comment]
@JVillator0 sorry for late reply, which nuxt.js version you are using? I find the major version is using vue2, maybe you should use 1.x version
```bash
npm i vue-split-carousel@1
```
