### ISSUE TITLE
Global integration need more documentation

### ISSUE THREAD

**Issue by djcaesar9114** [Aaron00101010/vue-split-carousel#5]
I tried a lot of things, it just doesn't work...
I tried to write exactly what was written (https://github.com/Aaron00101010/vue-split-carousel#global-component), it didn't work, so I added this (https://github.com/Aaron00101010/vue-split-carousel#local-component) and I had something showing, but all the images are one above the other.
I also tried this (https://github.com/Aaron00101010/vue-split-carousel#local-component) onyl, the console told me it didn't find the component.

We (at least I) need more explanation, maybe with a full basic example.

**Comment by Aaron00101010** [comment]
@djcaesar9114  playground is an example
