### ISSUE TITLE
Need information on accepted values

### ISSUE THREAD

**Issue by djcaesar9114** [Aaron00101010/vue-split-carousel#6]
The props have "-" for "accepted values", but what does it mean? I tried setting a percentage for height, and it didn't work. Should I only put pixel numbers?

**Comment by Aaron00101010** [comment]
@djcaesar9114 sorry for late reply
"accepted values" means exact value that can set
"-" means only limit value type
height props only accpect a number, unit is 'px'.
```vue
   <SplitCarousel style="height:20vh" v-bind="option">
      <SplitCarouselItem v-for="item in itemAmount" :key="item">
        <div class="box">{{ item }}</div>
      </SplitCarouselItem>
    </SplitCarousel>
```
also you can set height like above.
I would imporve this in next version
